apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: portworx-operator
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./portworx/portworx-operator
  prune: true