apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: portworx-storagecluster
  namespace: flux-system
spec:
  dependsOn:
    - name: portworx-operator
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./portworx/clusters/px-flux-eksdemo
  prune: true
  wait: true