apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: storageclasses
  namespace: flux-system
spec:
  dependsOn:
    - name: portworx-storagecluster
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./portworx/storageclasses
  prune: true